### ISSUE TITLE
Some saves are not workable in Apollo due to mounted save data being inside a sub directory

### ISSUE THREAD

**Issue by MODDEDWARFARE** [bucanero/apollo-ps4#22] opened 2022-01-19 21:25 UTC
Some save files for games like Dying Light store their decrypted save files in a directory. This appears to be a problem for Apollo, as the app seems to only be looking for a file in the root of the mounted save directory. So if the save is contained within a sub folder the app doesn't allow the save to be correctly resigned, exported or imported. 

![img1](https://user-images.githubusercontent.com/74997351/150215960-a0c446a1-b9f8-483d-960f-b09f47ec2575.png)
![img2](https://user-images.githubusercontent.com/74997351/150215964-575410da-3239-4d0e-9198-5ac44fbad4c0.png)

**Comment by bucanero** [comment] 2022-01-19 22:04
Hi, thanks for reporting this issue.

Could you export a .Zip out of this "Dying Light" save-game, so I can replicate the issue and fix it for the next version?

Just select "Export savegame to Zip", and select either USB or HDD. Then attach the `0000xxx.zip` file here. Thanks!

**Comment by MODDEDWARFARE** [comment] 2022-01-19 23:21
No prob, hope this helps.
[00000001.zip](https://github.com/bucanero/apollo-ps4/files/7901126/00000001.zip)

**Comment by bucanero** [comment] 2022-01-20 15:43
no, the issue is about the sub-folder structure. But keep in mind, the "Copy save game" and "Export save to Zip" options should work fine even if you have sub-folders and inner files.

The only 2 options that won't work properly are:
- Export single save files
- Import single decrypted save files

**Comment by bucanero** [comment] 2022-01-28 16:16
This should be fixed in v1.0.0

**Closed** 2022-01-28 16:17 UTC
Labels: bug
